symbol_map = {
  "reliance industries": "RELIANCE.NS",
  "tata consultancy services": "TCS.NS",
  "hdfc bank": "HDFCBANK.NS",
  "icici bank": "ICICIBANK.NS",
  "infosys": "INFY.NS",
  "larsen & toubro": "LT.NS",
  "itc": "ITC.NS",
  "state bank of india": "SBIN.NS",
  "bharti airtel": "BHARTIARTL.NS",
  "axis bank": "AXISBANK.NS",
  "hcl technologies": "HCLTECH.NS",
  "kotak mahindra bank": "KOTAKBANK.NS",
  "hindustan unilever": "HINDUNILVR.NS",
  "bajaj finance": "BAJFINANCE.NS",
  "adani enterprises": "ADANIENT.NS",
  "wipro": "WIPRO.NS",
  "adani green energy": "ADANIGREEN.NS",
  "adani ports and sez": "ADANIPORTS.NS",
  "sun pharmaceutical": "SUNPHARMA.NS",
  "ntpc": "NTPC.NS",
  "ultratech cement": "ULTRACEMCO.NS",
  "titan company": "TITAN.NS",
  "power grid corp": "POWERGRID.NS",
  "maruti suzuki": "MARUTI.NS",
  "bajaj finserv": "BAJAJFINSV.NS",
  "jsw steel": "JSWSTEEL.NS",
  "tata steel": "TATASTEEL.NS",
  "coal india": "COALINDIA.NS",
  "hindalco industries": "HINDALCO.NS",
  "mahindra & mahindra": "M&M.NS",
  "britannia industries": "BRITANNIA.NS",
  "nestle india": "NESTLEIND.NS",
  "cipla": "CIPLA.NS",
  "bharat electronics": "BEL.NS",
  "grasim industries": "GRASIM.NS",
  "divi's laboratories": "DIVISLAB.NS",
  "dr. reddy's labs": "DRREDDY.NS",
  "tech mahindra": "TECHM.NS",
  "asian paints": "ASIANPAINT.NS",
  "bajaj auto": "BAJAJ-AUTO.NS",
  "eicher motors": "EICHERMOT.NS",
  "tata motors": "TATAMOTORS.NS",
  "shree cement": "SHREECEM.NS",
  "hero motocorp": "HEROMOTOCO.NS",
  "indusind bank": "INDUSINDBK.NS",
  "dlf": "DLF.NS",
  "zomato": "ZOMATO.NS",
  "sbi life insurance": "SBILIFE.NS",
  "hdfc life": "HDFCLIFE.NS",
  "icici lombard": "ICICIGI.NS",
  "icici prudential life": "ICICIPRULI.NS",
  "adani total gas": "ATGL.NS",
  "ongc": "ONGC.NS",
  "tata consumer products": "TATACONSUM.NS",
  "pidilite industries": "PIDILITIND.NS",
  "apollo hospitals": "APOLLOHOSP.NS",
  "ambuja cements": "AMBUJACEM.NS",
  "indraprastha gas": "IGL.NS",
  "havells india": "HAVELLS.NS",
  "berger paints": "BERGEPAINT.NS",
  "cholamandalam finance": "CHOLAFIN.NS",
  "bharat forge": "BHARATFORG.NS",
  "srf ltd": "SRF.NS",
  "tvs motor company": "TVSMOTOR.NS",
  "tata power": "TATAPOWER.NS",
  "gail": "GAIL.NS",
  "siemens": "SIEMENS.NS",
  "colgate palmolive": "COLPAL.NS",
  "page industries": "PAGEIND.NS",
  "united spirits": "MCDOWELL-N.NS",
  "indian oil": "IOC.NS",
  "godrej consumer": "GODREJCP.NS",
  "icici securities": "ISEC.NS",
  "canara bank": "CANBK.NS",
  "bank of baroda": "BANKBARODA.NS",
  "union bank of india": "UNIONBANK.NS",
  "punjab national bank": "PNB.NS",
  "adani wilmar": "AWL.NS",
  "jsw energy": "JSWENERGY.NS",
  "torrent power": "TORNTPOWER.NS",
  "dixon technologies": "DIXON.NS",
  "rec ltd": "RECLTD.NS",
  "nhpc": "NHPC.NS",
  "indian railway finance": "IRFC.NS",
  "lupin": "LUPIN.NS",
  "jindal steel & power": "JINDALSTEL.NS",
  "gland pharma": "GLAND.NS",
  "indigo (interglobe aviation)": "INDIGO.NS",
  "muthoot finance": "MUTHOOTFIN.NS",
  "manappuram finance": "MANAPPURAM.NS",
  "bharat petroleum": "BPCL.NS",
  "irctc": "IRCTC.NS",
  "zydus lifesciences": "ZYDUSLIFE.NS",
  "bharat heavy electricals": "BHEL.NS",
  "bosch india": "BOSCHLTD.NS",
  "power finance corporation": "PFC.NS",
  "vedanta": "VEDL.NS",
  "oil & natural gas": "ONGC.NS",
  "dabur india": "DABUR.NS",
  "dr reddy’s laboratories": "DRREDDY.NS",
  "bharat petroleum": "BPCL.NS",
  "power grid": "POWERGRID.NS",
  "ashok leyland": "ASHOKLEY.NS",
  "bosch ltd": "BOSCHLTD.NS",
  "samvardhana motherson": "MOTHERSUMI.NS",
  "bharat heavy electricals": "BHEL.NS",
  "kpitt technologies": "KPITTECH.NS",
  "cholanmandalam": "CHOLAFIN.NS"
}

