const companyList = [
  "Reliance Industries",
  "Tata Consultancy Services",
  "HDFC Bank",
  "ICICI Bank",
  "Infosys",
  "Larsen & Toubro",
  "ITC",
  "State Bank of India",
  "Bharti Airtel",
  "Axis Bank",
  "HCL Technologies",
  "Kotak Mahindra Bank",
  "Hindustan Unilever",
  "Bajaj Finance",
  "Adani Enterprises",
  "Wipro",
  "Adani Green Energy",
  "Adani Ports and SEZ",
  "Sun Pharmaceutical",
  "NTPC",
  "UltraTech Cement",
  "Titan Company",
  "Power Grid Corp",
  "Maruti Suzuki",
  "Bajaj Finserv",
  "JSW Steel",
  "Tata Steel",
  "Coal India",
  "Hindalco Industries",
  "Mahindra & Mahindra",
  "Britannia Industries",
  "Nestle India",
  "Cipla",
  "Bharat Electronics",
  "Grasim Industries",
  "Divi's Laboratories",
  "Dr. Reddy's Labs",
  "Tech Mahindra",
  "Asian Paints",
  "Bajaj Auto",
  "Eicher Motors",
  "Tata Motors",
  "Shree Cement",
  "Hero MotoCorp",
  "IndusInd Bank",
  "DLF",
  "Zomato",
  "SBI Life Insurance",
  "HDFC Life",
  "ICICI Lombard",
  "ICICI Prudential Life",
  "Adani Total Gas",
  "ONGC",
  "Tata Consumer Products",
  "Pidilite Industries",
  "Apollo Hospitals",
  "Ambuja Cements",
  "Indraprastha Gas",
  "Havells India",
  "Berger Paints",
  "Cholamandalam Finance",
  "Bharat Forge",
  "SRF Ltd",
  "TVS Motor Company",
  "Tata Power",
  "GAIL",
  "Siemens",
  "Colgate Palmolive",
  "Page Industries",
  "United Spirits",
  "Indian Oil",
  "Godrej Consumer",
  "ICICI Securities",
  "Canara Bank",
  "Bank of Baroda",
  "Union Bank of India",
  "Punjab National Bank",
  "Adani Wilmar",
  "JSW Energy",
  "Torrent Power",
  "Dixon Technologies",
  "REC Ltd",
  "NHPC",
  "Indian Railway Finance",
  "Lupin",
  "Jindal Steel & Power",
  "Gland Pharma",
  "Indigo (Interglobe Aviation)",
  "Muthoot Finance",
  "Manappuram Finance",
  "Bharat Petroleum",
  "IRCTC",
  "Zydus Lifesciences"
]

export default companyList